export enum UserRegistrationStepEnum {
  NOT_REGISTERED = "NOT_REGISTERED",
  CLAN_CHOSEN = "CLAN_CHOSEN",
  CREATE_CLAN = "CREATE_CLAN",
  CLAN_REGISTERED = "CLAN_REGISTERED",
  USER_REGISTER = "USER_REGISTER",
  USER_SAVED = "USER_SAVED",
}